### ISSUE TITLE
Twitter cards & default image in form

### ISSUE THREAD

**Issue by tdorey** [cogdog/truwriter#10]
Hi Alan,

I *finally* updated to newest version and two things seems to have gone sideways. For the default image in the form, I'm getting the alt tag instead of the image and the way posts are coming up in tweets seems wrong. It is not highlighting info about the new post, but about the overall site. It was working better before the update. I haven't gone in yet to try to figure out what has changed...

![image](https://user-images.githubusercontent.com/18656532/27019558-635d8336-4eee-11e7-9ab7-6c4ca0ea3136.png)

![image](https://user-images.githubusercontent.com/18656532/27019615-f60d4874-4eee-11e7-996b-a08a8929be24.png)

**Comment by cogdog** [comment]
It's not possible to fully diagnose w/o seeing your theme files, so these are just some guesses.

For the missing image in the writing form it looks like maybe something is missing in the template page. The URL for the img tag has no value for the src="" 

`<img src="" alt="article banner image" id="headerthumb" />`

whereas on my test site, I get a thumbnail URL

`<img src="http://splot.ca/writer/files/2014/12/default-header-150x150.jpg" alt="article banner image" id="headerthumb" />`

Have you tried resetting the default in the options? Does it show there?

The problem with your twitter cards may be because you have the JetPack OpenGraph settings turned on and it is over-riding the information I coded to provide Writer specific cards. I could not find the post referenced in your screenshot, but am testing other posts on your site and it works -- I suggesting using https://cards-dev.twitter.com/validator to test the cards- the problem may be the missing default image

This is what the cards should be generating https://twitter.com/cogdog/status/874639107212836864

I can't tell much more from the outside.

**Comment by tdorey** [comment]
Thanks for looking into these things. I’ll take a look this weekend and see if I can solve them.
