### ISSUE TITLE
get_currentuserinfo deprecated

### ISSUE THREAD

**Issue by twelch555** [cogdog/truwriter#11]
Hi Alan, you are probably already on top of this. I had debug turned on for some troubleshooting and encountered the following notice:

PHP Notice:  get_currentuserinfo is <strong>deprecated</strong> since version 4.5.0! Use wp_get_current_user() instead. in /var/www/html/wp-includes/functions.php on line 3839

Cheers,
t

**Comment by cogdog** [comment]
Hi Troy, I am guessing you are still using older versions of the theme; that was updated a while ago across all the SPLOTs- see line 1498 in [the current functions.php](https://github.com/cogdog/truwriter/blob/master/functions.php)

```
function truwriter_check_user( $allowed='writer' ) {
	// checks if the current logged in user is who we expect
   $current_user = wp_get_current_user();
	
	// return check of match
	return ( $current_user->user_login == $allowed );
}
```
There's been a lot of improvements since that first version on trubox ;-)

**Comment by twelch555** [comment]
My apologies sir. I thought we were up to date, clearly we need to 'splaudit' our versions.
