### ISSUE TITLE
Tru writer header image in the form

### ISSUE THREAD

**Issue by mcandrewa** [cogdog/truwriter#16]
Hi Alan,

We're loving your TRU templates here at CU Boulder are we get our Domain of One's Own project up and running through Reclaim Hosting. But I did run into a little issue that I don't know how to fix. 

In the form in the TRU Writer template, the "set header image" button seems to be broken. Nothing happens when I click that button; it does not open the window to select an image for the header. I have tried it in Chrome, FireFox, and Safari. I have re-installed the template as well. I am hoping to use this template through Reclaim Hosting's Domain of One's Own instance here at CU Boulder in the next couple of weeks. Could you help with this?

Here is my test site where I'm having trouble. 
http://writer.mcandrew.buffscreate.net/write/ 

Thanks!
Amanda 
amanda.mcandrew@colorado.edu

**Comment by cogdog** [comment]
Hi Amanda,

I can see something is missing because of a script error on the write page, and that prevents the scripts from running on the media button.

When you say you re-installed the template, did you do this from the Reclaim Installer or manually updating from here? If the latter, are you sure you updated all the files? The one the seems to be perhaps not updated is in the `includes/` directory.

I've been making changes to the theme and have not had a lot of people testing (so thanks). Two small things to check.

1. In your TRU Writer Options, make sure you have selected existing pages for the Welcome Desk and the Writer form (listed under the Special Pages section).  Save the options.
2. Try going to your Dashboard, and look for Permalinks under Settings. Just click save (this cleans up a few issues).

If none of this works, I will try and think of other things that might be wrong.

Thanks for being interested in the theme.

**Comment by mcandrewa** [comment]
Thanks for such a quick response Alan. Yes I only re-installed from the Reclaim installer, as I didn’t know how to add the theme from elsewhere. But I just figured that out and the header image button is working.

So, I’m all set for now!

Amanda

**Comment by cogdog** [comment]
Ok, that's good. I will have to check their installer, it might be missing a file.

**Comment by mcandrewa** [comment]
That would be great, as we’re hoping to promote this template to our writing faculty.

Thanks again for your help!
Amanda
